import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from shop.models import Category, Product

# ---------------------------------------------------------------------------
# Données fictives — mêmes produits que dans l’ancien PRODUCTS
# ---------------------------------------------------------------------------

PRODUCTS_DATA = [
    # ── Figurines ──────────────────────────────────────────────────────────
    {
        "slug": "figurine-ace-portgas",
        "name": "Figurine Portgas D. Ace",
        "category": "Figurines",
        "price": 15000,
        "badge": "Populaire",
        "stock": True,
        "color": "brand-dark",
        "style": "Ace",
        "popularity": 99,
        "image": "images/products/figurine-ace.jpg",
        "description": "Figurine collector One Piece — Portgas D. Ace, le commandant de la 2e division de Barbe Blanche. Effet flammes spectaculaire, socle détaillé. Hauteur 26 cm.",
        "tags": "one piece, ace, collector",
        "is_popular": True,
    },
    {
        "slug": "figurine-naruto-hokage",
        "name": "Figurine Naruto Hokage",
        "category": "Figurines",
        "price": 18500,
        "badge": "Populaire",
        "stock": True,
        "color": "brand-dark",
        "style": "Naruto",
        "popularity": 98,
        "image": "",
        "description": "Figurine collector de Naruto en tenue Hokage. Finition premium, socle inclus. Hauteur 22 cm.",
        "tags": "shonen, naruto, collector",
        "is_popular": True,
    },
    {
        "slug": "figurine-goku-ultra-instinct",
        "name": "Figurine Goku Ultra Instinct",
        "category": "Figurines",
        "price": 22000,
        "badge": "Édition",
        "stock": True,
        "color": "brand",
        "style": "Goku",
        "popularity": 95,
        "image": "",
        "description": "Figurine articulée Dragon Ball Super — Goku en mode Ultra Instinct avec effet d'aura lumineux. Hauteur 28 cm.",
        "tags": "dragon ball, goku, collector",
        "is_popular": False,
    },
    {
        "slug": "figurine-demon-slayer-tanjiro",
        "name": "Figurine Tanjiro Kamado",
        "category": "Figurines",
        "price": 15000,
        "badge": "Nouveau",
        "stock": True,
        "color": "brand-dark",
        "style": "Tanjiro",
        "popularity": 91,
        "image": "",
        "description": "Figurine Demon Slayer — Tanjiro en position de combat avec katana. Édition collector limitée.",
        "tags": "demon slayer, kimetsu, collector",
        "is_popular": False,
    },
    {
        "slug": "figurine-one-piece-luffy-gear5",
        "name": "Figurine Luffy Gear 5",
        "category": "Figurines",
        "price": 25000,
        "badge": "Rare",
        "stock": False,
        "color": "brand-soft",
        "style": "Luffy",
        "popularity": 96,
        "image": "",
        "description": "Figurine One Piece — Monkey D. Luffy transformation Gear 5. Pièce rare très convoitée par les collectionneurs.",
        "tags": "one piece, luffy, rare",
        "is_popular": False,
    },
    # ── Vêtements ──────────────────────────────────────────────────────────
    {
        "slug": "haori-ace-one-piece",
        "name": "Haori Ace — One Piece",
        "category": "Vêtements",
        "price": 12000,
        "badge": "Bestseller",
        "stock": True,
        "color": "brand-dark",
        "style": "Ace",
        "popularity": 97,
        "image": "images/products/haori-ace.jpg",
        "description": "Haori kimono japonais One Piece — motif flammes rouge et noir inspiré de Portgas D. Ace, emblème des Pirates de Barbe Blanche au dos. Tissu léger et respirant. Tailles S à XXL.",
        "tags": "one piece, haori, ace, kimono",
        "is_popular": False,
    },
    {
        "slug": "haori-bleach-vasto-lorde",
        "name": "Haori Bleach — Vasto Lorde",
        "category": "Vêtements",
        "price": 12000,
        "badge": "Nouveau",
        "stock": True,
        "color": "brand-dark",
        "style": "Bleach",
        "popularity": 94,
        "image": "images/products/haori-bleach.jpg",
        "description": "Haori kimono japonais Bleach — motif démon Vasto Lorde rouge et noir. Imprimé haute résolution. Tissu léger et respirant. Tailles S à XXL.",
        "tags": "bleach, haori, vasto lorde, kimono",
        "is_popular": False,
    },
    {
        "slug": "hoodie-akatsuki-oversize",
        "name": "Hoodie Akatsuki Oversize",
        "category": "Vêtements",
        "price": 18000,
        "badge": "Premium",
        "stock": True,
        "color": "brand-dark",
        "style": "Akatsuki",
        "popularity": 93,
        "image": "",
        "description": "Hoodie noir premium avec broderie nuage rouge Akatsuki dans le dos. Coupe oversize confortable. Tailles S à XXL.",
        "tags": "naruto, streetwear, hoodie",
        "is_popular": False,
    },
    {
        "slug": "tshirt-one-piece-luffy-vintage",
        "name": "T-shirt Luffy Vintage",
        "category": "Vêtements",
        "price": 8500,
        "badge": "Stock",
        "stock": True,
        "color": "brand",
        "style": "Vintage",
        "popularity": 87,
        "image": "",
        "description": "T-shirt coton épais — graphique vintage Luffy effet usé. Style streetwear japonais. Disponible en blanc et noir.",
        "tags": "one piece, streetwear, t-shirt",
        "is_popular": False,
    },
    {
        "slug": "tshirt-attack-on-titan-scout",
        "name": "T-shirt Scout Regiment",
        "category": "Vêtements",
        "price": 9000,
        "badge": "Stock",
        "stock": True,
        "color": "brand-soft",
        "style": "Scout",
        "popularity": 82,
        "image": "",
        "description": "T-shirt Attack on Titan — logo du Corps d'Exploration brodé sur la poitrine. Coton respirant, coupe moderne.",
        "tags": "attack on titan, aot, scout",
        "is_popular": False,
    },
    # ── Mangas ─────────────────────────────────────────────────────────────
    {
        "slug": "manga-jjk-tome-1",
        "name": "Jujutsu Kaisen — Tome 1",
        "category": "Mangas",
        "price": 4500,
        "badge": "Classique",
        "stock": True,
        "color": "brand-soft",
        "style": "JJK",
        "popularity": 89,
        "image": "",
        "description": "Le début de l'aventure de Yuji Itadori. Édition française VF. Couverture cartonnée collector.",
        "tags": "jjk, jujutsu, shonen",
        "is_popular": False,
    },
    {
        "slug": "manga-demon-slayer-edition-speciale",
        "name": "Demon Slayer — Édition Spéciale",
        "category": "Mangas",
        "price": 7500,
        "badge": "Édition",
        "stock": True,
        "color": "brand",
        "style": "Kimetsu",
        "popularity": 92,
        "image": "",
        "description": "Coffret collector Demon Slayer tomes 1 à 3. Avec artbook exclusif et illustration bonus inédite.",
        "tags": "demon slayer, coffret, collector",
        "is_popular": False,
    },
    {
        "slug": "manga-solo-leveling-tome-1",
        "name": "Solo Leveling — Tome 1",
        "category": "Mangas",
        "price": 5000,
        "badge": "Tendance",
        "stock": True,
        "color": "brand-dark",
        "style": "Solo",
        "popularity": 94,
        "image": "",
        "description": "Le manhwa phénomène enfin en format livre. Sung Jinwoo commence son ascension. Traduction française officielle.",
        "tags": "solo leveling, manhwa, action",
        "is_popular": False,
    },
    {
        "slug": "manga-one-piece-tome-100",
        "name": "One Piece — Tome 100",
        "category": "Mangas",
        "price": 6000,
        "badge": "Collector",
        "stock": False,
        "color": "brand",
        "style": "OP-100",
        "popularity": 96,
        "image": "",
        "description": "Le tome historique numéro 100 de One Piece. Couverture spéciale gold foil. Pièce de collection incontournable.",
        "tags": "one piece, collector, milestone",
        "is_popular": False,
    },
    # ── Accessoires ────────────────────────────────────────────────────────
    {
        "slug": "porte-cle-ryuk-death-note",
        "name": "Porte-clé Ryuk — Death Note",
        "category": "Accessoires",
        "price": 2000,
        "badge": "Populaire",
        "stock": True,
        "color": "brand-dark",
        "style": "Ryuk",
        "popularity": 90,
        "image": "images/products/porte-cle-ryuk.jpg",
        "description": "Porte-clé chibi PVC Ryuk — Death Note. Sangle noire avec anneau doré. Finition soignée, idéal pour sac ou clés. Hauteur 6 cm.",
        "tags": "death note, ryuk, porte-clé",
        "is_popular": False,
    },
    {
        "slug": "porte-cles-aot-trio",
        "name": "Porte-clés Trio AoT — Eren, Mikasa, Livaï",
        "category": "Accessoires",
        "price": 2000,
        "badge": "Populaire",
        "stock": True,
        "color": "brand",
        "style": "AoT",
        "popularity": 88,
        "image": "images/products/porte-cles-aot.jpg",
        "description": "Lot de 3 porte-clés chibi PVC — Eren, Mikasa et Livaï (L'Attaque des Titans). Sangle rouge « Fight » et anneau doré. Parfait en trio ou à partager.",
        "tags": "attack on titan, aot, porte-clés, trio",
        "is_popular": False,
    },
    {
        "slug": "poster-wanted-one-piece",
        "name": "Poster Wanted One Piece",
        "category": "Accessoires",
        "price": 1500,
        "badge": "Déco",
        "stock": True,
        "color": "brand-soft",
        "style": "Wanted",
        "popularity": 86,
        "image": "",
        "description": "Set de 2 posters Wanted One Piece style parchemin vieilli. Format A4 (21 × 29,7 cm). Papier épais qualité affiche. Idéal pour décoration murale.",
        "tags": "one piece, poster, wanted, déco",
        "is_popular": False,
    },
    {
        "slug": "porte-cles-jjk-sukuna",
        "name": "Porte-clés Sukuna",
        "category": "Accessoires",
        "price": 2000,
        "badge": "Mini",
        "stock": True,
        "color": "brand",
        "style": "Sukuna",
        "popularity": 71,
        "image": "",
        "description": "Porte-clés acrylique double face — Ryomen Sukuna. Finition brillante, 6 cm. Livraison en pochette cadeau.",
        "tags": "porte-clés, jjk, sukuna",
        "is_popular": False,
    },
    {
        "slug": "tote-bag-manga-panel",
        "name": "Tote Bag Manga Panel",
        "category": "Accessoires",
        "price": 4000,
        "badge": "Goodies",
        "stock": True,
        "color": "brand-soft",
        "style": "Panel",
        "popularity": 73,
        "image": "",
        "description": "Tote bag en coton épais avec impression de panels manga en noir et blanc. Capacité 15L. Anse longue.",
        "tags": "tote bag, manga, goodies",
        "is_popular": False,
    },
    {
        "slug": "poster-demon-slayer-neon",
        "name": "Poster Demon Slayer Néon",
        "category": "Accessoires",
        "price": 3500,
        "badge": "Déco",
        "stock": True,
        "color": "brand-dark",
        "style": "Poster",
        "popularity": 67,
        "image": "",
        "description": "Affiche 50×70cm — composition néon Demon Slayer. Papier mat qualité galerie. Idéal pour chambre ou salon.",
        "tags": "poster, déco, demon slayer",
        "is_popular": False,
    },
    {
        "slug": "mug-anime-store-dakar",
        "name": "Mug Anime Store Dakar",
        "category": "Accessoires",
        "price": 3000,
        "badge": "Exclusif",
        "stock": True,
        "color": "brand-dark",
        "style": "Mug",
        "popularity": 65,
        "image": "",
        "description": "Mug 33cl exclusif Anime Store Dakar. Impression céramique haute résistance. Résistant au lave-vaisselle.",
        "tags": "mug, exclusif, goodies",
        "is_popular": False,
    },
    {
        "slug": "pin-dragon-ball-set",
        "name": "Set de Pins Dragon Ball",
        "category": "Accessoires",
        "price": 3500,
        "badge": "Bundle",
        "stock": True,
        "color": "brand-soft",
        "style": "Pins",
        "popularity": 69,
        "image": "",
        "description": "Set de 4 pins Dragon Ball — Goku, Vegeta, Piccolo, Frieza. Finition émaillée, dorure or. Présentoir inclus.",
        "tags": "pins, dragon ball, bundle",
        "is_popular": False,
    },
    {
        "slug": "pack-decouverte-otaku",
        "name": "Pack Découverte Otaku",
        "category": "Accessoires",
        "price": 12000,
        "badge": "Promo",
        "stock": True,
        "color": "brand",
        "style": "Pack",
        "popularity": 85,
        "image": "",
        "description": "Pack surprise Otaku : 1 manga au choix, 1 poster, 1 porte-clés et 1 sticker pack. Le cadeau idéal pour un fan.",
        "tags": "pack, cadeau, surprise",
        "is_popular": False,
    },
]


def seed():
    # 1. Créer les catégories
    categories_names = sorted({p["category"] for p in PRODUCTS_DATA})
    categories = {}
    for name in categories_names:
        cat, _ = Category.objects.get_or_create(
            name=name,
            defaults={"slug": name.lower().replace(" ", "-")},
        )
        categories[name] = cat

    # 2. Créer les produits
    for data in PRODUCTS_DATA:
        cat_name = data.pop("category")
        category = categories[cat_name]

        Product.objects.update_or_create(
            slug=data["slug"],
            defaults={
                "category": category,
                "name": data["name"],
                "price": data["price"],
                "badge": data.get("badge", ""),
                "stock": data.get("stock", True),
                "color": data.get("color", "brand-dark"),
                "style": data.get("style", ""),
                "popularity": data.get("popularity", 50),
                "image": data.get("image", ""),
                "description": data.get("description", ""),
                "tags": data.get("tags", ""),
                "is_popular": data.get("is_popular", False),
            },
        )

    print("✅ Produits et catégories créés en base.")


if __name__ == "__main__":
    seed()
