# Generated by Django 5.2.17 on 2026-09-12 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('stock', models.BooleanField(default=True, help_text='Produit en stock ?')),
                ('badge', models.CharField(blank=True, default='', help_text='Ex: Populaire, Nouveau, Édition, Rare, etc.', max_length=50)),
                ('color', models.CharField(blank=True, default='brand-dark', help_text='brand-dark, brand, brand-soft', max_length=50)),
                ('style', models.CharField(blank=True, default='', help_text='Nom du style / univers (Ace, Naruto, Goku, etc.)', max_length=100)),
                ('popularity', models.PositiveIntegerField(default=50, help_text="Plus c'est grand, plus c'est mis en avant")),
                ('image', models.CharField(blank=True, default='', help_text='Chemin relatif, ex: images/products/figurine-ace.jpg', max_length=255)),
                ('tags', models.CharField(blank=True, default='', help_text='Tags séparés par des virgules (one piece, ace, collector)', max_length=255)),
                ('is_available', models.BooleanField(default=True, help_text='Produit visible sur le site (vs retiré)')),
                ('is_popular', models.BooleanField(default=False, help_text='Affiché dans les produits mis en avant (home)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-popularity', 'name'],
            },
        ),
    ]
